---
title: "p8105_hw5_wm2473"
output: github_document
date: "2022-11-14"
---

```{r}
library(tidyverse)
library(readxl)
library(rvest)
library(ggplot2)
set.seed(1)

```

Problem 2
```{r}
#Describe the raw data.?? 
hd = read_csv("homicide-data.csv") %>% 
  janitor::clean_names() %>% 
   mutate(city_state = str_c(city,",", state), 
         homicides = case_when(disposition == "Closed without arrest" ~ "unsolved homicides", disposition == "Open/No arrest" ~ "unsolved homicides", disposition == "Closed by arrest" ~ "solved homicides")) %>%
  filter(city_state != "TulsaAL") %>% 
  relocate(city_state)


hd %>% 
  group_by(city_state, homicides) %>% 
  count() %>% 
  knitr::kable()
```


```{r}
Baltimore = hd %>%
  filter(city_state == "Baltimore,MD") %>%  
  summarise(
    unsolved = sum(homicides == "unsolved homicides"),
    n = n()
  )

Baltimore_test = 
  prop.test(
    x = Baltimore %>% pull(unsolved),
    n = Baltimore %>% pull(n))

Baltimore_test %>% 
  broom::tidy() 
```

Prop.test for each of the city
```{r}
city_proptest = function(city_df){
  city_summarize = city_df %>%
  summarise(
    unsolved = sum(homicides == "unsolved homicides"),
    n = n())
  
  city_test = 
  prop.test(
    x = city_summarize %>% pull(unsolved),
    n = city_summarize %>% pull(n))
  
  return(city_test)
}
```

```{r}
nested_df = hd %>%
  nest(alldata = uid:homicides) %>% 
  mutate(
    test_results = map(alldata, city_proptest),
    cleanresults = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, cleanresults) %>% 
  unnest(cleanresults) %>% 
  select(city_state, estimate, starts_with("conf"))
```
Creat the plot
```{r}
nested_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point()+geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        plot.title = element_text(hjust = 0.5)) +
  labs(title = "Estimate vale among different city with errorbar",
       x = "City(State)",
       y = "Estimate") 
```

Problem 3
t_test function
```{r}
norm_and_t_test = function(mu) {
  sim_data = tibble(
    x = rnorm(n = 30, mean = mu, sd = 5),
  )  
    t.test(sim_data, mu =0, conf.level = 0.95, alternative = "two.sided") %>%
    broom::tidy() %>% 
    select(estimate, p.value)
}

sim_results_df = 
  expand_grid(
    mu = c(1, 2, 3, 4, 5, 6),
    itr = 1:5000) %>% 
  mutate(results = map(mu, norm_and_t_test)) %>% 
  unnest(results)
```

First plot(mu vs. proportion of reject)
```{r}
sim_results_df %>% 
  mutate(decision = case_when(p.value < 0.05 ~ "reject", p.value >= 0.05 ~ "fail_to_reject")) %>% 
  group_by(mu) %>% 
  summarize(n_obs = n(), prop_reject = sum(decision == "reject") / n_obs * 100)%>%
  ggplot(aes(x = mu, y = prop_reject)) + geom_point() +geom_path(alpha = .5)+labs(
    title = "Power vs. True mean",
    x = "True mean",
    y = "Power")

```


```{r}
```

